
spring:
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
         uri: https://github.com/ryanjbaxter/beginngers-guide-to-spring-cloud-config
server:
  port: 8888
         #uri: file:///Users/ryanjbaxter/git-repos/ryanjbaxter/talks/beginners-guide/beginngers-guide-to-spring-cloud-config
